# Generated by Django 4.2.27 on 2026-02-02 02:33

from django.db import migrations, models
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash of file content for deduplication', max_length=64)),
                ('is_duplicate', models.BooleanField(default=False, help_text='True if this file shares storage with another file')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['original_filename'], name='files_file_origina_63129f_idx'), models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'), models.Index(fields=['size'], name='files_file_size_6009e9_idx'), models.Index(fields=['uploaded_at'], name='files_file_uploade_726d10_idx'), models.Index(fields=['content_hash'], name='files_file_content_adaf85_idx')],
            },
        ),
    ]
